# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/meow/working/CourseWork2018_2019

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/meow/working/CourseWork2018_2019

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meow/working/CourseWork2018_2019/CMakeFiles /home/meow/working/CourseWork2018_2019/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meow/working/CourseWork2018_2019/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DisplayImage

# Build rule for target.
DisplayImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DisplayImage
.PHONY : DisplayImage

# fast build rule for target.
DisplayImage/fast:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/build
.PHONY : DisplayImage/fast

#=============================================================================
# Target rules for targets named ImgManipInterface

# Build rule for target.
ImgManipInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImgManipInterface
.PHONY : ImgManipInterface

# fast build rule for target.
ImgManipInterface/fast:
	$(MAKE) -f CMakeFiles/ImgManipInterface.dir/build.make CMakeFiles/ImgManipInterface.dir/build
.PHONY : ImgManipInterface/fast

#=============================================================================
# Target rules for targets named CrossFindingInterface

# Build rule for target.
CrossFindingInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CrossFindingInterface
.PHONY : CrossFindingInterface

# fast build rule for target.
CrossFindingInterface/fast:
	$(MAKE) -f CMakeFiles/CrossFindingInterface.dir/build.make CMakeFiles/CrossFindingInterface.dir/build
.PHONY : CrossFindingInterface/fast

#=============================================================================
# Target rules for targets named FocusFindingInterface

# Build rule for target.
FocusFindingInterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FocusFindingInterface
.PHONY : FocusFindingInterface

# fast build rule for target.
FocusFindingInterface/fast:
	$(MAKE) -f CMakeFiles/FocusFindingInterface.dir/build.make CMakeFiles/FocusFindingInterface.dir/build
.PHONY : FocusFindingInterface/fast

CrossFindingRealize.o: CrossFindingRealize.cpp.o

.PHONY : CrossFindingRealize.o

# target to build an object file
CrossFindingRealize.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/CrossFindingRealize.cpp.o
	$(MAKE) -f CMakeFiles/CrossFindingInterface.dir/build.make CMakeFiles/CrossFindingInterface.dir/CrossFindingRealize.cpp.o
.PHONY : CrossFindingRealize.cpp.o

CrossFindingRealize.i: CrossFindingRealize.cpp.i

.PHONY : CrossFindingRealize.i

# target to preprocess a source file
CrossFindingRealize.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/CrossFindingRealize.cpp.i
	$(MAKE) -f CMakeFiles/CrossFindingInterface.dir/build.make CMakeFiles/CrossFindingInterface.dir/CrossFindingRealize.cpp.i
.PHONY : CrossFindingRealize.cpp.i

CrossFindingRealize.s: CrossFindingRealize.cpp.s

.PHONY : CrossFindingRealize.s

# target to generate assembly for a file
CrossFindingRealize.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/CrossFindingRealize.cpp.s
	$(MAKE) -f CMakeFiles/CrossFindingInterface.dir/build.make CMakeFiles/CrossFindingInterface.dir/CrossFindingRealize.cpp.s
.PHONY : CrossFindingRealize.cpp.s

FocusFindingRealize.o: FocusFindingRealize.cpp.o

.PHONY : FocusFindingRealize.o

# target to build an object file
FocusFindingRealize.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/FocusFindingRealize.cpp.o
	$(MAKE) -f CMakeFiles/FocusFindingInterface.dir/build.make CMakeFiles/FocusFindingInterface.dir/FocusFindingRealize.cpp.o
.PHONY : FocusFindingRealize.cpp.o

FocusFindingRealize.i: FocusFindingRealize.cpp.i

.PHONY : FocusFindingRealize.i

# target to preprocess a source file
FocusFindingRealize.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/FocusFindingRealize.cpp.i
	$(MAKE) -f CMakeFiles/FocusFindingInterface.dir/build.make CMakeFiles/FocusFindingInterface.dir/FocusFindingRealize.cpp.i
.PHONY : FocusFindingRealize.cpp.i

FocusFindingRealize.s: FocusFindingRealize.cpp.s

.PHONY : FocusFindingRealize.s

# target to generate assembly for a file
FocusFindingRealize.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/FocusFindingRealize.cpp.s
	$(MAKE) -f CMakeFiles/FocusFindingInterface.dir/build.make CMakeFiles/FocusFindingInterface.dir/FocusFindingRealize.cpp.s
.PHONY : FocusFindingRealize.cpp.s

ImgManipRealize.o: ImgManipRealize.cpp.o

.PHONY : ImgManipRealize.o

# target to build an object file
ImgManipRealize.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/ImgManipRealize.cpp.o
	$(MAKE) -f CMakeFiles/ImgManipInterface.dir/build.make CMakeFiles/ImgManipInterface.dir/ImgManipRealize.cpp.o
.PHONY : ImgManipRealize.cpp.o

ImgManipRealize.i: ImgManipRealize.cpp.i

.PHONY : ImgManipRealize.i

# target to preprocess a source file
ImgManipRealize.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/ImgManipRealize.cpp.i
	$(MAKE) -f CMakeFiles/ImgManipInterface.dir/build.make CMakeFiles/ImgManipInterface.dir/ImgManipRealize.cpp.i
.PHONY : ImgManipRealize.cpp.i

ImgManipRealize.s: ImgManipRealize.cpp.s

.PHONY : ImgManipRealize.s

# target to generate assembly for a file
ImgManipRealize.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/ImgManipRealize.cpp.s
	$(MAKE) -f CMakeFiles/ImgManipInterface.dir/build.make CMakeFiles/ImgManipInterface.dir/ImgManipRealize.cpp.s
.PHONY : ImgManipRealize.cpp.s

Start.o: Start.cpp.o

.PHONY : Start.o

# target to build an object file
Start.cpp.o:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/Start.cpp.o
.PHONY : Start.cpp.o

Start.i: Start.cpp.i

.PHONY : Start.i

# target to preprocess a source file
Start.cpp.i:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/Start.cpp.i
.PHONY : Start.cpp.i

Start.s: Start.cpp.s

.PHONY : Start.s

# target to generate assembly for a file
Start.cpp.s:
	$(MAKE) -f CMakeFiles/DisplayImage.dir/build.make CMakeFiles/DisplayImage.dir/Start.cpp.s
.PHONY : Start.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DisplayImage"
	@echo "... rebuild_cache"
	@echo "... ImgManipInterface"
	@echo "... edit_cache"
	@echo "... CrossFindingInterface"
	@echo "... FocusFindingInterface"
	@echo "... CrossFindingRealize.o"
	@echo "... CrossFindingRealize.i"
	@echo "... CrossFindingRealize.s"
	@echo "... FocusFindingRealize.o"
	@echo "... FocusFindingRealize.i"
	@echo "... FocusFindingRealize.s"
	@echo "... ImgManipRealize.o"
	@echo "... ImgManipRealize.i"
	@echo "... ImgManipRealize.s"
	@echo "... Start.o"
	@echo "... Start.i"
	@echo "... Start.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

